In [1]:
import pandas as pd
import os

In [2]:
path=""
year=['2016', '2017', '2018', '2019', '2020']
team=['HT', 'LT', 'SK', 'LG', 'NC', 'KT', 'HH', 'OB', 'SS', 'WO']

In [4]:
#open files
path="2019"+"_convert"
filename="convert_bigcon_"+year[-2]+"_"

index_front = ["G_ID", "GDAY_DS", "T_ID", "VS_T_ID", "HEADER_NO", "TB_SC",
             "WHIP", "LOB", "ERA", "FIP", "H_9", "K_9", "BB_9", "HR_9",
             "oAVG", "oSLG", "oOBP", "P_WHIP_RT", "P2_WHIP_RT", "CB_WHIP_RT",
             "AVG", "OBP", "SLG", "OPS", "RC", "GPA", "BA", "SECA", "TA", "XR", "ISO",
             "wOBA", "P_HRA_RT", "DER", "PF", "H_A", "WLS", "PITCHER_INNING", "PITCHER_ER", "HITTER_AB", "HITTER_HIT"]

index_back = ["WHIP", "LOB", "ERA", "FIP", "H_9", "K_9", "BB_9", "HR_9",
             "oAVG", "oSLG", "oOBP", "P_WHIP_RT", "P2_WHIP_RT", "CB_WHIP_RT",
             "AVG", "OBP", "SLG", "OPS", "RC", "GPA", "BA", "SECA", "TA", "XR", "ISO",
             "wOBA", "P_HRA_RT", "DER", "PF", "H_A", "WLS", "PITCHER_INNING", "PITCHER_ER", "HITTER_AB", "HITTER_HIT"]

index_back=["vs_"+i for i in index_back]

#index_back[0]=index_back[0][3:]

dfs=[]

df = pd.DataFrame(columns = index_front)

for i in team:
    filepath=path+"\\"+filename+i+".csv"
    file = pd.read_csv(filepath, index_col=None, header=0)
     
    dfs.append(file)

df = pd.concat(dfs, axis=0, ignore_index=True)

In [5]:
df=df.sort_values(by=['G_ID'], axis=0)
df

,Unnamed: 0,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,WHIP,LOB,ERA,...,wOBA,P_HRA_RT,DER,PF,H_A,WLS,PITCHER_INNING,PITCHER_ER,HITTER_AB,HITTER_HIT
1008,0,20190323HHOB0,20190323,OB,HH,0,B,1.889,0.778,4.000,...,0.435,0.200,0.586,939,1,1,9.000,4,34,12
864,0,20190323HHOB0,20190323,HH,OB,0,T,1.375,0.625,5.625,...,0.210,0.000,0.792,939,0,0,8.000,5,28,3
720,0,20190323KTSK0,20190323,KT,SK,0,T,1.750,0.625,6.750,...,0.334,0.143,0.750,971,0,0,8.000,6,31,8
288,0,20190323KTSK0,20190323,SK,KT,0,B,1.333,0.755,4.000,...,0.314,0.200,0.680,971,1,1,9.000,4,36,9
432,0,20190323LGHT0,20190323,LG,HT,0,T,0.667,1.000,0.000,...,0.441,0.250,0.870,1004,0,1,9.000,0,31,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,143,20190930SKHH0,20190930,SK,HH,0,T,1.000,0.921,2.000,...,0.416,0.400,0.724,1025,0,1,9.000,2,33,9
719,143,20191001NCOB0,20191001,NC,OB,0,T,1.920,0.625,5.400,...,0.408,0.250,0.571,939,0,0,8.333,5,43,17
1151,143,20191001NCOB0,20191001,OB,NC,0,B,2.111,0.737,5.000,...,0.242,0.167,0.528,939,1,1,9.000,5,36,9
287,143,20191001WOLT0,20191001,LT,WO,0,B,1.222,0.727,1.000,...,0.379,0.267,0.692,1041,1,0,9.000,1,40,15
1439,143,20191001WOLT0,20191001,WO,LT,0,T,1.111,0.900,1.000,...,0.289,0.300,0.679,1041,0,1,9.000,1,35,8

In [6]:
new_df = pd.DataFrame(columns = index_front+index_back[1:])

for idx,_row in enumerate(df.iterrows()):
    if (idx%2==0):
        eve_row=pd.DataFrame(df[idx:idx+1], columns=index_front)
        eve_row=eve_row.reset_index()
        eve_row=eve_row.drop(columns=['index'])
    else:
        odd_row=pd.DataFrame(df[idx:idx+1], columns=index_front)
        odd_row=odd_row.drop(columns=index_front[:6])
        odd_row.columns=index_back
        odd_row=odd_row.reset_index()
        odd_row=odd_row.drop(columns=['index'])        
        
        row=pd.DataFrame(pd.concat([eve_row, odd_row], axis=1))
        
        new_df=new_df.append(row, ignore_index=True)[row.columns.tolist()]
print(new_df)
new_df.to_csv("combined_"+str(2019)+".csv")

              G_ID   GDAY_DS T_ID VS_T_ID HEADER_NO TB_SC   WHIP    LOB   ERA  \
0    20190323HHOB0  20190323   OB      HH         0     B  1.889  0.778  4.00
1    20190323KTSK0  20190323   KT      SK         0     T  1.750  0.625  6.75
2    20190323LGHT0  20190323   LG      HT         0     T  0.667  1.000  0.00
3    20190323SSNC0  20190323   NC      SS         0     B  0.667  1.000  0.00
4    20190323WOLT0  20190323   WO      LT         0     T  0.889  0.556  3.00
..             ...       ...  ...     ...       ...   ...    ...    ...   ...
715  20190929WOLT0  20190929   LT      WO         0     B  0.778  0.556  3.00
716  20190930LTLG0  20190930   LG      LT         0     B  0.667  1.000  0.00
717  20190930SKHH0  20190930   HH      SK         0     B  1.667  0.662  6.00
718  20191001NCOB0  20191001   NC      OB         0     T  1.920  0.625  5.40
719  20191001WOLT0  20191001   LT      WO         0     B  1.222  0.727  1.00

        FIP  ...  vs_wOBA  vs_P_HRA_RT  vs_DER  vs_PF  vs_H_A  vs_WLS  \
0    16.444  ...    0.210        0.000   0.792    939       0       0
1    42.750  ...    0.314        0.200   0.680    971       1       1
2    10.667  ...    0.248        0.231   0.579   1004       1       0
3     4.889  ...    0.462        0.375   0.762   1035       0       0
4     3.556  ...    0.171        0.000   0.625   1041       1       0
..      ...  ...      ...          ...     ...    ...     ...     ...
715  11.111  ...    0.252        0.300   0.720   1041       0       1
716   8.111  ...    0.284        0.000   0.739    939       0       0
717  26.000  ...    0.416        0.400   0.724   1025       0       1
718   1.560  ...    0.242        0.167   0.528    939       1       1
719   7.000  ...    0.289        0.300   0.679   1041       0       1

    vs_PITCHER_INNING  vs_PITCHER_ER  vs_HITTER_AB  vs_HITTER_HIT
0                 8.0              5            28              3
1                 9.0              4            36              9
2                 9.0              2            35              7
3                 8.0              7            31              8
4                 9.0              7            29              4
..                ...            ...           ...            ...
715               9.0              1            32              5
716               8.0              2            27              6
717               9.0              2            33              9
718               9.0              5            36              9
719               9.0              1            35              8

[720 rows x 76 columns]

In [7]:
def combiner(path, filename):
    year=['2016', '2017', '2018', '2019', '2020']
    team=['HT', 'LT', 'SK', 'LG', 'NC', 'KT', 'HH', 'OB', 'SS', 'WO']
    #open files
    #path="_test_convert"
    #filename="_test_convert_bigcon_"+year[-2]+"_"

    index_front = ["G_ID", "GDAY_DS", "T_ID", "VS_T_ID", "HEADER_NO", "TB_SC",
             "WHIP", "LOB", "ERA", "FIP", "H_9", "K_9", "BB_9", "HR_9",
             "oAVG", "oSLG", "oOBP", "P_WHIP_RT", "P2_WHIP_RT", "CB_WHIP_RT",
             "AVG", "OBP", "SLG", "OPS", "RC", "GPA", "BA", "SECA", "TA", "XR", "ISO",
             "wOBA", "P_HRA_RT", "DER", "PF", "H_A", "WLS", "PITCHER_INNING", "PITCHER_ER", "HITTER_AB", "HITTER_HIT"]

    index_back = ["WHIP", "LOB", "ERA", "FIP", "H_9", "K_9", "BB_9", "HR_9",
             "oAVG", "oSLG", "oOBP", "P_WHIP_RT", "P2_WHIP_RT", "CB_WHIP_RT",
             "AVG", "OBP", "SLG", "OPS", "RC", "GPA", "BA", "SECA", "TA", "XR", "ISO",
             "wOBA", "P_HRA_RT", "DER", "PF", "H_A", "WLS", "PITCHER_INNING", "PITCHER_ER", "HITTER_AB", "HITTER_HIT"]

    index_back=["vs_"+i for i in index_back]

    #index_back[0]=index_back[0][3:]
    if (os.path.isdir(os.getcwd()+"\\combined")==False):
        os.mkdir('combined')
    #dfs=[]       <=========================== 이걸 for문 안으로 넣어서 각 연도별 combined이 되도록 수정했습니다. -태민-

    df = pd.DataFrame(columns = index_front)
    for y in year:
        dfs = []
        for i in team:
            filepath=str(y)+path+"\\"+filename+str(y)+"_"+i+".csv"
            file = pd.read_csv(filepath, index_col=None, header=0)
     
            dfs.append(file)

        df = pd.concat(dfs, axis=0, ignore_index=True)
        df=df.sort_values(by=['G_ID'], axis=0)
    
        new_df = pd.DataFrame(columns = index_front+index_back[1:])

        for idx,_row in enumerate(df.iterrows()):
            if (idx%2==0):
                eve_row=pd.DataFrame(df[idx:idx+1], columns=index_front)
                eve_row=eve_row.reset_index()
                eve_row=eve_row.drop(columns=['index'])
            else:
                odd_row=pd.DataFrame(df[idx:idx+1], columns=index_front)
                odd_row=odd_row.drop(columns=index_front[:6])
                odd_row.columns=index_back
                odd_row=odd_row.reset_index()
                odd_row=odd_row.drop(columns=['index'])        
        
                row=pd.DataFrame(pd.concat([eve_row, odd_row], axis=1))
        
                new_df=new_df.append(row, ignore_index=True)[row.columns.tolist()]
        #print(new_df)
        new_df.to_csv("combined\combined_"+str(y)+".csv")

In [8]:
combiner("_convert","convert_bigcon_")